name: 'ECS Deployment'
description: 'Github action using fabfuel/ecs-deploy script for ecs deployments'
inputs:
  action:
    description: 'Action to perform. Defaults to deploy'
    required: true
    default: 'deploy'
  cluster:
    description: 'Cluster name where service/task will be deployed'
    required: true
  target:
    description: 'Service or task name to perform this action on'
    required: true
  tag:
    description: 'Applicable to the deploy action. Changes the tag of all images in all containers in the task definition to the tag given'
    required: false
  image:
    description: 'Applicable to the deploy action. Updates the image of a specific container. Pass the value as "[container-name] [image-name]:[image-tag]". You can pass multiple values as comma-separated'
    required: false
  task:
    description: 'Applicable to the deploy action. Updates the target service with a new task definition, which can either be an ARN, a family name with revision, or just a family name (you will get the most recent revision)'
    required: false
  env_vars:
    description: 'Set one or more environment variables. The syntax is "[container] [ENV_VAR_NAME] [ENV_VAR_VALUE]". You can set multiple env vars by comma-separating them as "[container] [ENV_VAR_NAME] [ENV_VAR_VALUE], [container] [ANOTHER_ENV_VAR_NAME] [ANOTHER_ENV_VAR_VALUE]"'
    required: false
  exclusive_env:
    description: 'To reset all existing environment variables of a task definition. Set to "true" to enable'
    required: false
  secrets:
    description: 'Set one or more secrets from parameter store or secrets manager. The syntax is "[container] [SECRET_NAME] [SECRET_ARN]". You can set multiple env vars by comma-separating them as "[container] [SECRET_NAME] [SECRET_ARN], [container] [ANOTHER_SECRET_NAME] [ANOTHER_SECRET_ARN]"'
    required: false
  exclusive_secrets:
    description: 'To reset all existing secrets (secret environment variables) of a task definition. Set to "true" to enable'
    required: false
  command:
    description: 'To change the command of a specific container. The syntax is "[container] "[command]" "'
    required: false
  task_role:
    description: "To change or set the role, the service's task should run as, specify the role ARN here"
    required: false
  ignore_warnings:
    description: 'To ignore warnings that come up during deployment and continue to wait until the deployment times out, set this to "true"'
    required: false
  timeout:
    description: "How long to wait for things to time out (in seconds)"
    required: false
    default: "300"
  scale_value:
    description: "Applicable to the scale action. Determines how many running tasks you wish to have on the service"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'